export default {
    Success: 0,
    Fail: 1,
    Login: 2,
    Logout: 3,
    HallChat: 4,
    GetHallDialog: 5,
    GetRooms: 6,
    CreateRoom: 7,
    EnterRoom: 8,
    LeaveRoom: 9,
    DelRoom: 10,
    RoomChat: 11,
    GetPlayer: 12,
    GetPlayers: 13,
    PlayerRename: 14,
    SetPlayerStatus: 15,
    SetReady: 16,
    MakeStep: 17,
    RetractStep: 18,
    Surrender: 19,
    AskDraw: 20,
    GameOver: 21
}